include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TextTimePrefs

TextTimePrefs_FILES = TextTimePrefsRootListController.m
TextTimePrefs_FRAMEWORKS = UIKit
TextTimePrefs_PRIVATE_FRAMEWORKS = Preferences
TextTimePrefs_INSTALL_PATH = /Library/PreferenceBundles
TextTimePrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
